"use client";

import { FadeUp } from "@/components/animation/MotionWrappers";
import { fetchTelegramOverview, type TelegramOverviewResponse } from "@/lib/api";
import { getToken } from "@/lib/auth";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

export default function TelegramDashboardPage() {
  const router = useRouter();
  const [data, setData] = useState<TelegramOverviewResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const token = getToken();
    if (!token) {
      router.replace("/login");
      return;
    }

    const load = async () => {
      try {
        const response = await fetchTelegramOverview(token);
        setData(response);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to load Telegram data");
      }
    };

    void load();
  }, [router]);

  return (
    <div className="p-8 space-y-8 bg-slate-100 min-h-full">
      <FadeUp>
        <div>
          <h1 className="text-3xl font-bold text-slate-900">Telegram Pipeline</h1>
          <p className="text-slate-500">Messages, extracted tasks, and memory entries generated by Telegram webhook traffic.</p>
        </div>
      </FadeUp>

      {error ? <p className="text-rose-600 font-semibold">{error}</p> : null}

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
        <section className="bg-white border rounded-2xl p-5">
          <h2 className="font-bold text-slate-900 mb-4">Telegram Messages</h2>
          <div className="space-y-3 max-h-[420px] overflow-auto">
            {data?.messages.map((message) => (
              <div key={message.id} className="border rounded-xl p-3">
                <p className="text-xs text-slate-400">{new Date(message.created_at).toLocaleString()}</p>
                <p className="text-sm text-slate-700 break-all">{message.raw_payload}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="bg-white border rounded-2xl p-5">
          <h2 className="font-bold text-slate-900 mb-4">Extracted Tasks</h2>
          <div className="space-y-3 max-h-[420px] overflow-auto">
            {data?.tasks.map((task) => (
              <div key={task.id} className="border rounded-xl p-3">
                <p className="text-sm font-semibold text-slate-900">{task.title ?? task.description}</p>
                <p className="text-xs text-slate-600">{task.description}</p>
                <p className="text-xs text-slate-400">Priority: {task.priority} · Confidence: {Math.round(task.confidence_score * 100)}%</p>
              </div>
            ))}
          </div>
        </section>

        <section className="bg-white border rounded-2xl p-5">
          <h2 className="font-bold text-slate-900 mb-4">Created Memories</h2>
          <div className="space-y-3 max-h-[420px] overflow-auto">
            {data?.memories.map((memory) => (
              <div key={memory.id} className="border rounded-xl p-3">
                <p className="text-xs text-slate-400">{new Date(memory.created_at).toLocaleString()}</p>
                <p className="text-sm text-slate-700">{memory.text}</p>
              </div>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}
